[package]
name = "stilts-lang"
version = "0.1.0"
description = "The parser for stilts"
edition = "2021"
license = "MIT"

[dependencies]
miette = "5.9"
proc-macro2 = { version = "1", features = ["span-locations"] }
syn = { version = "2", features = ["full", "extra-traits"] }
thiserror = "1"
