[book]
authors = ["Jack Morrison"]
language = "en"
multilingual = false
src = "src"
title = "Stilts"

#[output.pandoc]
#optional = true

#[output.pandoc.profile.pdf]
#output-file = "output.pdf"
#to = "latex"
#pdf-engine="xelatex"

#[output.pandoc.profile.pdf.variables]
#mainfont = "DejaVu Serif"
#sansfont = "DejaVu Sans"
#monofont = "JetBrainsMono Nerd Font"

#[output.wordcount]
#optional = true

[output.html]
site-url = "https://atrociously.github.io/stilts"
git-repository-url = "https://github.com/Atrociously/stilts"
additional-css = ["theme/lines.css"]
additional-js = ["theme/highlightjs-line-numbers.min.js", "theme/linenum.js", "vis/plotly.min.js", "vis/boxit.js"]

[output.html.playground]
runnable = false
